De-RxJS-ing
RenovoSolutions/TypeScript-Angular-Components pull request #366
Opened 2016-11-07 19:40 UTC by TheOriginalJosh

removing RxJS infavor of using clearTimeout and setTimeout. cutting down on complexity and removing nested subscribes.

clearTimeout being null should be fix in zone.js as of beta.12. 

https://github.com/angular/angular/issues/7680

2016-11-07 19:47 UTC, KorinaGraber requested changes
This should work. But note that I included a related fix in the previous PR, which we still want.

2016-11-07 19:47 UTC, SamGraber commented on source/behaviors/autosave/autosave.tests.ts
> -		it('should not save if the form becomes pristine immediately before saving', () => {
We still want this. This was another thing that got corrected/added with the previous PR

2016-11-07 19:47 UTC, SamGraber commented on source/behaviors/autosave/autosave.ts
> -		if (!this.canAutosave()) {
We still want this. This was another thing that got corrected/added with the previous PR

2016-11-07 19:58 UTC, SamGraber commented on source/behaviors/autosave/autosave.ts
> +import { Directive, Input, Self, AfterViewInit, HostListener, ElementRef } from '@angular/core';
Why the ElementRef import?

2016-11-07 19:58 UTC, SamGraber commented on source/behaviors/autosave/autosave.ts
> -		if (!this.canAutosave()) {
https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/366/commits/b9cd3c11269c5d99c188e33f40405c3b5747932c

2016-11-07 19:58 UTC, SamGraber commented on source/behaviors/autosave/autosave.tests.ts
> -		it('should not save if the form becomes pristine immediately before saving', () => {
https://github.com/RenovoSolutions/TypeScript-Angular-Components/pull/366/commits/b9cd3c11269c5d99c188e33f40405c3b5747932c

2016-11-07 19:58 UTC, KorinaGraber approved these changes

2016-11-08 19:12 UTC, SamGraber commented
Merge conflicts

2016-11-08 19:13 UTC, KorinaGraber requested changes
Merge conflicts

2016-11-08 20:18 UTC, KorinaGraber approved these changes

2016-11-08 20:43 UTC, merged