Validation changes and additions
RenovoSolutions/TypeScript-Angular-Components pull request #401
Opened 2017-02-22 20:42 UTC by jbeck8176

-added naming to forms when adding to parent as child controls
-added recluse form. To be used when needed to break the nesting of rlForm.

2017-02-22 20:50 UTC, KorinaGraber requested changes

2017-02-22 20:50 UTC, SamGraber commented on source/components/form/form.ts
> +		return !this.form.invalid;
Were you going to revert this since `pending` is actually another state that's not exactly valid?

2017-02-23 14:56 UTC, jbeck8176 commented on source/components/form/form.ts
> +		return !this.form.invalid;
Missed that one, got the other tho

2017-02-23 15:06 UTC, KorinaGraber approved these changes

2017-02-23 15:20 UTC, BrentWMiller commented on package.json
> +  "version": "4.2.1",
Just leaving a note that this version will need updated again.

2017-02-23 15:33 UTC, merged